/*
This file was generated from ion source. Do not edit.
*/
import * as Location from '../Location';
import * as Null from './Null';
import * as SpreadElement from '../SpreadElement';
import * as Expression from '../Expression';
import * as _Array from './Array';
import * as Pattern from '../Pattern';
import * as Identifier from '../Identifier';
import * as IfStatement from '../IfStatement';
import * as BlockStatement from '../BlockStatement';
import * as Boolean from './Boolean';
import * as Number from './Number';
import * as String from './String';
import * as Property from '../Property';
import * as RestElement from '../RestElement';
import * as Literal from '../Literal';
import * as CatchClause from '../CatchClause';
import * as Integer from './Integer';
import * as Class from './Class';
export type Location_Location_or_ion_Null_Null = Location.Location | Null.Null;
export type SpreadElement_SpreadElement_or_ion_Null_Null = SpreadElement.SpreadElement | Null.Null;
export type Expression_Expression_or_ion_types_SpreadElement_SpreadElement_or_ion_Null_Null = Expression.Expression | (SpreadElement.SpreadElement | Null.Null);
export type ___TemplateReference___ = _Array.Array<Expression.Expression | (SpreadElement.SpreadElement | Null.Null)>;
export type Pattern_Pattern_or_ion_Null_Null = Pattern.Pattern | Null.Null;
export type Identifier_Identifier_or_ion_Null_Null = Identifier.Identifier | Null.Null;
export type IfStatement_IfStatement_or_ion_Null_Null = IfStatement.IfStatement | Null.Null;
export type BlockStatement_BlockStatement_or_ion_types_IfStatement_IfStatement_or_ion_Null_Null = BlockStatement.BlockStatement | (IfStatement.IfStatement | Null.Null);
export type ion_Boolean_Boolean_or_ion_Null_Null = Boolean.Boolean | Null.Null;
export type ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = Number.Number | (Boolean.Boolean | Null.Null);
export type ion_String_String_or_ion_types_ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = String.String | (Number.Number | (Boolean.Boolean | Null.Null));
export type Identifier_Identifier_or_Expression_Expression = Identifier.Identifier | Expression.Expression;
export type Expression_Expression_or_Identifier_Identifier = Expression.Expression | Identifier.Identifier;
export type Property_Property_or_SpreadElement_SpreadElement = Property.Property | SpreadElement.SpreadElement;
export type Property_Property_or_RestElement_RestElement = Property.Property | RestElement.RestElement;
export type Expression_Expression_or_ion_Null_Null = Expression.Expression | Null.Null;
export type Literal_Literal_or_Identifier_Identifier = Literal.Literal | Identifier.Identifier;
export type Expression_Expression_or_Pattern_Pattern = Expression.Expression | Pattern.Pattern;
export type BlockStatement_BlockStatement_or_ion_Null_Null = BlockStatement.BlockStatement | Null.Null;
export type CatchClause_CatchClause_or_ion_Null_Null = CatchClause.CatchClause | Null.Null;
export type ion_Integer_Integer___gte_0_ = Integer.Integer;
export type func__class__ion_Class_Class_instance__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type func___returns_ion_String_String = undefined;
export type func_value__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type ion_String_String___length_lte_this_length_ = String.String;
export type func___returns_ion_types_ion_String_String___length_lte_this_length_ = undefined;
export type func_pattern__ion_String_String__returns_ion_Boolean_Boolean = undefined;